### ISSUE TITLE
Consider extending EventEmitter in addition to callbacks

### ISSUE THREAD

**Issue by ralphholzmann** [intrinio/intrinio-realtime-node-sdk#1]
Just switched to this instead of our own web socket implementation for IEX. One thing that struck me was the callback pattern for responding to quotes and errors. Would you ever consider having your class extend `EventEmitter`, so we could have a more node-like API? Something like:

```js
const socket = new IntrinioRealtime({
  username: config.INTRINIO_username,
  password: config.INTRINIO_password
});

socket.on('quote', (quote) => {});

socket.on('error', (err) => {});
```

I'd be happy to PR this as well.

**Comment by civilframe** [comment]
That's a great suggestion! I'd welcome your PR.
